services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment: { ZOOKEEPER_CLIENT_PORT: 2181 }

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 20

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint:
      - /bin/bash
      - -lc
    command:
      - |
        # Warten bis der Broker wirklich erreichbar ist (max 30 Versuche)
        for i in $(seq 1 30); do
          if kafka-topics --bootstrap-server kafka:29092 --list >/dev/null 2>&1; then
            break
          fi
          echo "Warte auf Kafka... ($$i)"
          sleep 2
        done

        # Topics idempotent anlegen
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists \
          --topic taxi_yellow --partitions 6 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists \
          --topic taxi_green  --partitions 6 --replication-factor 1

        echo "Topics angelegt."


  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: nyc
      POSTGRES_USER: nyc
      POSTGRES_PASSWORD: nyc
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ../sql/taxi_zone_lookup.csv:/docker-entrypoint-initdb.d/taxi_zone_lookup.csv:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nyc -d nyc"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  adminer:
    image: adminer
    ports: ["8082:8080"]

  producer:
    image: python:3.12-slim
    depends_on:
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    working_dir: /app
    environment:
      BOOTSTRAP: kafka:29092
      DATA_DIR: /app/data/parquet
      RATE: "0"
      DAY_GAP_SEC: "0"
      START_YEAR: "2025"
      TOPIC_Y: taxi_yellow
      TOPIC_G: taxi_green
      PYTHONUNBUFFERED: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_ROOT_USER_ACTION: ignore
    volumes:
      - ../:/app
    command: >
      bash -lc "
        pip install --no-cache-dir pandas pyarrow confluent-kafka &&
        python kafka/producer.py
      "

  spark:
    image: apache/spark:3.5.1
    depends_on:
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      PGTBL_Y: public.rides_yellow    # <— neu
      PGTBL_G: public.rides_green     # <— neu
      SPARK_MODE: client
      KAFKA: kafka:29092
      PGURL: jdbc:postgresql://postgres:5432/nyc
      PGUSR: nyc
      PGPW: nyc
      CHECKPOINT: /chk/taxi_pipe
    volumes:
      - ../:/app
      - ./chk:/chk
    command: >
      spark-submit
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.postgresql:postgresql:42.7.3
      /app/spark/spark_stream.py

  streamlit:
    image: python:3.12-slim
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    environment:
      DB_URL: postgresql+psycopg2://nyc:nyc@postgres:5432/nyc
      REFRESH_SEC: "10"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_ROOT_USER_ACTION: ignore
    volumes:
      - ../:/app
    command:
      - bash
      - -lc
      - |
        pip install --no-cache-dir streamlit sqlalchemy psycopg2-binary pandas streamlit-autorefresh
        streamlit run streamlit/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"


volumes:
  pgdata:
